language: node_js
node_js:
  - "11.13"
env:
  global:
    - NODE_ENV=test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run test-with-coverage
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
install:
  - npm install
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"